<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Oleseas-MacBook-Pro.local" name="TestNgSessions.ExpectExceptionConcept" tests="5" failures="0" timestamp="17 Aug 2020 21:54:54 GMT" time="0.010" errors="1">
  <testcase name="getNumbertest2" time="0.001" classname="TestNgSessions.ExpectExceptionConcept">
    <error type="org.testng.TestException" message="
Expected exception of type class java.lang.NullPointerException but got java.lang.ArithmeticException: / by zero">
      <![CDATA[org.testng.TestException: 
Expected exception of type class java.lang.NullPointerException but got java.lang.ArithmeticException: / by zero
at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
at org.testng.internal.Invoker.considerExceptions(Invoker.java:1130)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:615)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ArithmeticException: / by zero
at TestNgSessions.ExpectExceptionConcept.getNumbertest2(ExpectExceptionConcept.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
... 19 more
]]>
    </error>
  </testcase> <!-- getNumbertest2 -->
  <testcase name="getNumbertes4" time="0.007" classname="TestNgSessions.ExpectExceptionConcept"/>
  <testcase name="getNumbertest" time="0.001" classname="TestNgSessions.ExpectExceptionConcept"/>
  <testcase name="getNumbertest1" time="0.000" classname="TestNgSessions.ExpectExceptionConcept"/>
  <testcase name="getNumbertest3" time="0.001" classname="TestNgSessions.ExpectExceptionConcept"/>
</testsuite> <!-- TestNgSessions.ExpectExceptionConcept -->
